// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbsnnlhjhlifoqrvoixb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNic25ubGhqaGxpZm9xcnZvaXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDM0NzMsImV4cCI6MjA1ODM3OTQ3M30.oBrAIrr2Xtn6HshYUgnE6oEk_Lpl1BdD5EgoOR37Y8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});